import React from "react";
import Layout from "./components/Layout";
import ContentBlock from "./components/ContentBlock";
import ActionBar from "./components/ActionBar";

function App() {
  return (
    <Layout>
      <ActionBar />

      <ContentBlock
        heading="Auto Generated Block Heading"
        summary="Summary about this block and content generated below."
        content={[
          "This is a paragraph of generated content. It can be dynamic and injected by the AI agent.",
          "Another paragraph or bullet, depending on type.",
        ]}
        type="paragraph"
        actions={[
          { label: "Add Item", onClick: () => alert("Add clicked!") },
          { label: "Copy", onClick: () => alert("Copy clicked!") },
        ]}
      />
      <div className="h-8" />
      <ContentBlock
        heading="AI Suggestions"
        summary="Here are some bullet point suggestions generated by the AI."
        content={[
          "First suggestion bullet point.",
          "Second suggestion bullet point.",
          "Third suggestion bullet point.",
        ]}
        type="bullets"
        actions={[{ label: "Accept All", onClick: () => alert("Accepted!") }]}
      />
    </Layout>
  );
}

export default App;
